name: dotnet package

on: [push]

env:
  SOLUTION: EDSDK.NET.sln
  NUGET_REPO_URL: https://nuget.pkg.github.com/Motiony/index.json

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: [ '8.0.x' ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Install Dependencies
        run: dotnet restore ${{ env.SOLUTION }}

      - name: Build Project
        run: dotnet build ${{ env.SOLUTION }} --configuration Release

      - name: Tests
        run: dotnet test Tests/EDSDK.NET.Tests/EDSDK.NET.Tests.csproj --no-restore

      - name: Create the package
        run: dotnet pack EDSDK.NET/EDSDK.NET.csproj --configuration Release --no-restore

      - name: Publish the package to Repository
        run: dotnet nuget push ${{ env.PROJECT_FOLDER }}/bin/Release/*.nupkg --api-key ${{ secrets.MRRADIANNUGETSECRET }} --source ${{ env.NUGET_REPO_URL }}
